version: '3.8'
services:
  app:
    build:   
        context: .      
        dockerfile: Dockerfile
    container_name: vacinapet
    image: php:8.0
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
   
    depends_on:
      - redis
    networks:
      - laravel-9

    # nginx
  nginx:
      image: nginx:alpine
      restart: unless-stopped
      ports: 
          - "8989:80"
      volumes: 
          - ./:/var/www
          - ./docker/nginx/:/etc/nginx/conf.d/
      depends_on:
        - app 
      networks: 
          - laravel-9

  mysql:
    image: mysql:8.0
    container_name: vacinapet-mysql
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3388:3306"
    networks:
      - laravel-9
  

  redis:
      image: redis:latest
      networks:
          - laravel-9
networks:
    laravel-9:
        driver: bridge


