version: '3.8'
services:
  app:
    build:   
        context: .      
        dockerfile: Dockerfile
    container_name: app
    image: php:8.0
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:80"
      - "8080:80"
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - redis
    networks:
      - laravel-9 

    # nginx
  nginx:
      image: nginx:alpine
      restart: unless-stopped
      ports: 
          - "8989:80"
      volumes: 
          - ./:/var/www
          - ./docker/nginx/:/etc/nginx/conf.d/
      depends_on:
        - app 
      networks: 
          - laravel-9

  mysql:
    image: mysql
    container_name: vacinapet-mysql
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
       
    
    ports:
      - "3388:3306"
    networks:
      - laravel-9
  

  redis:
      image: redis:latest
      networks:
          - laravel-9
networks:
    laravel-9:
        driver: bridge